1059 padding margin accordions
hackforla/tdm-calculator pull request #1123
Opened 2022-04-14 03:19 UTC by jahpe777

Fixed padding/margins on accordions

Closes #1059

2022-04-21 06:12 UTC, fyliu requested changes
The fixes look great!
There's some extra lines and files that should probably be deleted.

2022-04-21 06:12 UTC, fyliu commented on server/db/migration/V20220413.2005__adjust_tooltips_1059.sql
> +{"id": "4", "name": "100% Affordable"}]',
These lines are not necessary to update the description. They can be safely deleted.
```suggestion
```

2022-04-21 06:12 UTC, fyliu commented on server/db/migration/V20220413.2005__adjust_tooltips_1059.sql
> +where calculationId = 1 and code = 'STRATEGY_TRANSIT_ACCESS_4'
These lines are extras from V20210526.1439__adjust_tooltips_827_832.sql. They can be safely deleted.
```suggestion
```

2022-04-21 06:12 UTC, fyliu commented on server/db/migration/V20220413.1837__rule_adjustments_1059.sql
> +WHERE calculationId = 1 and code in ('UNITS_HABIT_LT3', 'UNITS_HABIT_3', 'UNITS_HABIT_GT3')
This is a duplicate file with padding-bottom:0 that'll be overwritten later with the margin-bottom:0 version
```suggestion
```

2022-04-21 06:12 UTC, fyliu commented on server/db/migration/V20220413.1856__adjust_tooltips_1059.sql
> +where calculationId = 1 and code = 'STRATEGY_TRANSIT_ACCESS_4'
This is a duplicate file with padding-bottom:0 that'll be overwritten later with the margin-bottom:0 version. This file can be safely deleted.
```suggestion
```

2022-04-21 06:12 UTC, fyliu commented on server/db/migration/V20220413.1922__consolidate_bike_share_strategies_1059.sql
> +
This is a duplicate file with padding-bottom:0 that'll be overwritten later with the margin-bottom:0 version. This file can be safely deleted.
```suggestion
```

2022-05-09 00:56 UTC, jahpe777 commented
Updated sql files based on review by @fyliu

2022-05-12 03:48 UTC, jahpe777 commented
made edits based on Fangs comments for encouragement program strategy

2022-05-12 05:13 UTC, fyliu approved these changes
Looks good. Thanks for making the changes.

2022-05-12 05:14 UTC, merged